# Generated by Django 4.2.28 on 2026-04-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'autor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, unique=True)),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'editorial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('anio_publicacion', models.TextField()),
                ('no_paginas', models.PositiveSmallIntegerField()),
                ('edicion', models.CharField(max_length=100)),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'libro',
                'managed': False,
            },
        ),
    ]
