spring.application.name=repaso_SpringBoot_JWT

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/gestion_biblioteca_backup
spring.datasource.username=pruebas
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=YkI8p2m9rK+3WQZxE0pHDFI6U4qYj9Nq+uM0u0QnqG3sQFvYyzS/zqj1DL8bEFeH
jwt.expiration=86400000